/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FundsRouteImport } from './routes/funds'
import { Route as HoldingsRouteImport } from './routes/holdings'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as InstrumentSymbolRouteImport } from './routes/instrument.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsRoute = FundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsRoute = HoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentSymbolRoute = InstrumentSymbolRouteImport.update({
  id: '/instrument/$symbol',
  path: '/instrument/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/funds': typeof FundsRoute
  '/holdings': typeof HoldingsRoute
  '/orders': typeof OrdersRoute
  '/positions': typeof PositionsRoute
  '/watchlist': typeof WatchlistRoute
  '/instrument/$symbol': typeof InstrumentSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/funds': typeof FundsRoute
  '/holdings': typeof HoldingsRoute
  '/orders': typeof OrdersRoute
  '/positions': typeof PositionsRoute
  '/watchlist': typeof WatchlistRoute
  '/instrument/$symbol': typeof InstrumentSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/funds': typeof FundsRoute
  '/holdings': typeof HoldingsRoute
  '/orders': typeof OrdersRoute
  '/positions': typeof PositionsRoute
  '/watchlist': typeof WatchlistRoute
  '/instrument/$symbol': typeof InstrumentSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/funds'
    | '/holdings'
    | '/orders'
    | '/positions'
    | '/watchlist'
    | '/instrument/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/funds'
    | '/holdings'
    | '/orders'
    | '/positions'
    | '/watchlist'
    | '/instrument/$symbol'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/funds'
    | '/holdings'
    | '/orders'
    | '/positions'
    | '/watchlist'
    | '/instrument/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FundsRoute: typeof FundsRoute
  HoldingsRoute: typeof HoldingsRoute
  OrdersRoute: typeof OrdersRoute
  PositionsRoute: typeof PositionsRoute
  WatchlistRoute: typeof WatchlistRoute
  InstrumentSymbolRoute: typeof InstrumentSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds': {
      id: '/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof FundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings': {
      id: '/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof HoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instrument/$symbol': {
      id: '/instrument/$symbol'
      path: '/instrument/$symbol'
      fullPath: '/instrument/$symbol'
      preLoaderRoute: typeof InstrumentSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FundsRoute: FundsRoute,
  HoldingsRoute: HoldingsRoute,
  OrdersRoute: OrdersRoute,
  PositionsRoute: PositionsRoute,
  WatchlistRoute: WatchlistRoute,
  InstrumentSymbolRoute: InstrumentSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
